apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-niau
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-niau
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-niau
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-niau
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-niau
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-vqba-tenant/rhtap-demo-app/hacbs-test-project-niau@sha256:5cc07dd4055857218c599d3a46979a743f0b313826a65cd13faf34cca5c11d9b
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
